### ISSUE TITLE
Small improvement for readme

### ISSUE THREAD

**Issue by Menziess** [kasp3r/link-preview#13]
The **utf8_decode( )** function willl make sure that for example Russian characters get displayed properly. This is almost crucial when dealing with content that needs to be previewed coming from anywhere in the world.

A sentence like: "_Священная война (The Sacred War) - Alexandrov Red Army Choir_" would otherwise show up as "_Ð¡Ð²ÑÑÐµÐ½Ð½Ð°Ñ Ð²Ð¾Ð¹Ð½Ð° (The Sacred War) - Alexandrov Red Army Choir_".

**Comment by kasp3r** [comment]
This is similar issue to https://github.com/kasp3r/link-preview/pull/5 . utf8_decode enabled by default would break characters in other places where utf8 decoding is not needed. My suggestion is to deal with situation like this in you own codebase or please suggest universal solution/make a pull request.
This library is made in mind to leave all the possibilities for customization. One of the options how to implement your required utf8_decode functionality is to create custom Link model.
Create _Utf8DecodedLink_ class that extends _Link_ class. Rewrite _getTitle()_ functions to _return utf8_decode($this->title)_ . Then to use your custom Link model you do as this:

```
$linkPreview = new LinkPreview();
$utf8DecodedLink = new Utf8DecodedLink();
$generalParser = new GeneralParser(null, $utf8DecodedLink);
$linkPreview->addParser($generalParser);
$linkPreview->setUrl('http://github.com');
$parsed = $linkPreview->getParsed();
```
