### ISSUE TITLE
How to avoid blocked port

### ISSUE THREAD

**Issue by mavinothkumar** [kasp3r/link-preview#14]
Hi,
Is the plugin validating the blocked ports? For example, www.dinamalar.com is working, suppose if the user enters https://dinamalar.com then it will crash as the port 443 is not open on that website. How to fix this issue?

**Comment by kasp3r** [comment]
Hi,
This library is not silencing errors. It is using 3rd party library **guzzlehttp/guzzle** for network communication and in case of error that library is throwing an exception, so you can **catch an exception** yourself.

**Comment by mavinothkumar** [comment]
Ok thanks for your reply, why is it not crawling if I give www.facebook.com ? it's not taking www

**Comment by kasp3r** [comment]
You can try to catch an exception and check what the error message says.
