### ISSUE TITLE
http://www.retl-en-ligne.com/go i have a issue with this url it is giving me uploads/... path but i want image with the base url

### ISSUE THREAD

**Issue by maharajay** [kasp3r/link-preview#16]
@kasp3r  @edueo please look on it  http://www.retl-en-ligne.com/go i have a issue with this url it is giving me uploads/... path but i want image with the base url

**Comment by kasp3r** [comment]
You can do a check if url contains http and if not, then add it yourself.

**Comment by maharajay** [comment]
But sometimes it is not giving me images like Facebook developer  link
preview

Ajay Singh
