### ISSUE TITLE
YouTube no longer works

### ISSUE THREAD

**Issue by albertleao** [kasp3r/link-preview#3]
Message: Client error response [status code] 410 [reason phrase] Gone [url] http://gdata.youtube.com/feeds/api/videos/zCbfWGgp9qs?v=2&alt=jsonc

**Comment by kasp3r** [comment]
It looks like google deprecated v2 API. I will look into this ASAP. Thank you for reporting.

**Comment by albertleao** [comment]
No problem. I think it's still doable of you use yql

**Comment by kasp3r** [comment]
Fixed youtube parser. It is not using API anymore, but takes information from meta tags.
