### ISSUE TITLE
Whitespaces

### ISSUE THREAD

**Issue by alexschwarz89** [kasp3r/link-preview#7]
Some websites include many whitespaces in their tags. For example see the title tag of https://www.fressnapf.de/p/penthouse-arthur. 

Maybe apply a `trim` on all values? I did no pull request because there is another one open and maybe you have a better solution / more generic way or just want to include all whitespaces. So, just an issue and freedom to decide :dancer:

**Comment by kasp3r** [comment]
This is library with a purpose to get data, not to manage it. I would suggest to manipulate data yourself.

**Comment by alexschwarz89** [comment]
And I thought it was a library for link previews… ;-) 
Is there any reason where you want a link preview with tons of whitespaces? Anyway, just sayin, nvm
