### ISSUE TITLE
Redirects/requests with cookies

### ISSUE THREAD

**Issue by dusterio** [kasp3r/link-preview#8]
I noticed today that some links are not parsed correctly. Eg. Akamai specifies a cookie a shows a redirect ('Location' header) and then the next page expects to see the cookie.

Now I assume that link-preview doesn't store/use cookies so it's unable to visit the page. 

Given that Facebook and others do this just fine, I assume there are no legal/whatever requirements and this can be done.

Would you do it yourself or would you prefer a PR?

**Comment by dusterio** [comment]
I see that you are relying on very old version of guzzle - "guzzle/guzzle": "~3.8". This bug has been fixed in 2012 or so. Migrating to newer guzzle would solve the issue

**Comment by 33mhz** [comment]
This is very unfortunate. Thanks @dusterio for pulling it ahead. I'll use your fork.

**Comment by kasp3r** [comment]
Updated dependencies to the latest stable version. Please use v2.0.0
